/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from 'grpc';

export namespace anhuai {
    export namespace user {
        export namespace grpc {
            // 状态
            export enum Status {
                // 已启用
                ENABLED = 0,
                // 已停用
                DISABLED = 1,
                // 已删除
                DELETED = 2,
            }
            // 测试枚举
            export enum Season {
                // 春
                SPRING = 0,
                // 夏
                SUMMER = 1,
                // 秋
                AUTUMN = 2,
                // 冬
                WINTER = 3,
            }
        }
    }
}

